/**
 * The typed, validated view of everything editable.
 *
 * The DATA lives in `src/content/settings/*.json`, which is what the CMS at
 * /admin reads and writes. This module is the only thing that reads those
 * files: it validates them against a schema and hands components clean,
 * typed values. Components never touch JSON directly.
 *
 * Why validate: the CMS can write a malformed file (a cleared required field,
 * a mistyped URL). Validating here means `npm run build` fails with a precise
 * message instead of the site silently rendering an empty hero.
 *
 * TO CHANGE CONTENT: use /admin, or edit the JSON. Do not edit this file.
 */
import { z } from 'astro/zod';

import profileJson from '../content/settings/profile.json';
import socialJson from '../content/settings/social.json';
import skillsJson from '../content/settings/skills.json';
import resumeJson from '../content/settings/resume.json';

/** Fail the build with a message that names the file and the exact field. */
function parse<T extends z.ZodTypeAny>(schema: T, data: unknown, file: string): z.infer<T> {
  const result = schema.safeParse(data);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `  • ${i.path.join('.') || '(root)'}: ${i.message}`)
      .join('\n');
    throw new Error(
      `Content error in src/content/settings/${file}\n${issues}\n\n` +
        `Fix it at /admin, or edit the file directly.`,
    );
  }
  return result.data;
}

/* -------------------------------------------------------------------------
   Profile
   ------------------------------------------------------------------------- */
const profileSchema = z.object({
  name: z.string().min(1),
  initials: z.string().min(1).max(3),
  role: z.string().min(1),
  availability: z.string().default(''),
  tagline: z.string().min(1),
  intro: z.string().default(''),
  location: z.string().default(''),
  email: z.string().email(),
  summary: z.string().min(1).max(200),
  /** Empty means "no photo yet" — the hero renders a monogram instead. */
  photo: z.string().default(''),
  photoAlt: z.string().default(''),
  /** Empty means "no CV yet" — the download button is not rendered at all. */
  cv: z.string().default(''),
});

export const profile = parse(profileSchema, profileJson, 'profile.json');

export const shortName = profile.name.split(' ')[1] ?? profile.name;

/* -------------------------------------------------------------------------
   Social links

   An empty `url` means the link does not exist yet, so it is dropped entirely
   rather than rendered as a dead or apologetic link. Fill the URL in at /admin
   and it appears everywhere at once.
   ------------------------------------------------------------------------- */
export type SocialIcon = 'github' | 'linkedin' | 'mail' | 'x' | 'link';

const socialSchema = z.object({
  links: z.array(
    z.object({
      label: z.string().min(1),
      icon: z.enum(['github', 'linkedin', 'mail', 'x', 'link']),
      url: z.string().default(''),
    }),
  ),
});

const socialData = parse(socialSchema, socialJson, 'social.json');

export interface SocialLink {
  label: string;
  icon: SocialIcon;
  href: string;
  /** What to show as the link text: a handle, not a raw URL. */
  handle: string;
}

/** Turn a URL into something readable — "github.com/name", not the whole thing. */
function handleFor(url: string): string {
  try {
    const u = new URL(url);
    const path = u.pathname.replace(/\/+$/, '');
    return `${u.hostname.replace(/^www\./, '')}${path}`;
  } catch {
    return url;
  }
}

export const socials: SocialLink[] = [
  ...socialData.links
    .filter((l) => l.url.trim() !== '')
    .map((l) => ({
      label: l.label,
      icon: l.icon as SocialIcon,
      href: l.url.trim(),
      handle: handleFor(l.url.trim()),
    })),
  // Email is always available, and is always last: it is the fallback everyone
  // understands, and it should not be something you can accidentally delete.
  {
    label: 'Email',
    icon: 'mail' as SocialIcon,
    href: `mailto:${profile.email}`,
    handle: profile.email,
  },
];

/* -------------------------------------------------------------------------
   Skills
   ------------------------------------------------------------------------- */
const skillsSchema = z.object({
  groups: z.array(
    z.object({
      title: z.string().min(1),
      note: z.string().default(''),
      items: z.array(z.object({ name: z.string().min(1), detail: z.string().default('') })),
    }),
  ),
});

export const skillGroups = parse(skillsSchema, skillsJson, 'skills.json').groups;
export type SkillGroup = (typeof skillGroups)[number];

/* -------------------------------------------------------------------------
   Experience and education
   ------------------------------------------------------------------------- */
const entrySchema = z.object({
  title: z.string().min(1),
  organisation: z.string().min(1),
  location: z.string().default(''),
  period: z.string().default(''),
  summary: z.string().default(''),
  points: z.array(z.string()).default([]),
  tags: z.array(z.string()).default([]),
});

const resumeSchema = z.object({
  experience: z.array(entrySchema).default([]),
  education: z.array(entrySchema).default([]),
});

const resume = parse(resumeSchema, resumeJson, 'resume.json');

export type TimelineEntry = z.infer<typeof entrySchema>;
export const experience = resume.experience;
export const education = resume.education;

/* -------------------------------------------------------------------------
   Derived flags — presence of a file is the switch, never a separate boolean.
   Upload a photo and it appears; there is no second checkbox to forget.
   ------------------------------------------------------------------------- */
export const portrait = {
  available: profile.photo.trim() !== '',
  src: profile.photo.trim(),
  alt: profile.photoAlt.trim() || `Photograph of ${profile.name}`,
};

export const cv = {
  available: profile.cv.trim() !== '',
  path: profile.cv.trim(),
  filename: `${profile.name.replace(/\s+/g, '-')}-CV.pdf`,
};

/* -------------------------------------------------------------------------
   Navigation — structure, not content, so it stays in code.
   ------------------------------------------------------------------------- */
export const nav = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Projects', href: '/projects' },
  { label: 'Résumé', href: '/resume' },
  { label: 'Contact', href: '/contact' },
] as const;
